# Generated by Django 3.2.5 on 2021-07-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('relationship', models.CharField(choices=[('Aunty', 'Aunty'), ('Uncle', 'Uncle'), ('Cousin', 'Cousin'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather'), ('2nd Cousin', '2nd Cousin')], max_length=50)),
            ],
        ),
    ]
