# Generated by Django 3.2.5 on 2021-08-24 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(default=None, upload_to='img/')),
                ('image_title', models.CharField(default=None, max_length=50)),
                ('image_caption', models.CharField(default=None, max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.people')),
            ],
        ),
        migrations.RemoveField(
            model_name='media2',
            name='person',
        ),
        migrations.RemoveField(
            model_name='media',
            name='statement',
        ),
        migrations.RemoveField(
            model_name='media',
            name='uploaded_image',
        ),
        migrations.AddField(
            model_name='media',
            name='file_information',
            field=models.TextField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='file_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='uploaded_file',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Media2',
        ),
    ]
