# Generated by Django 3.2.5 on 2021-07-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20210705_0250'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='uploaded_image',
            field=models.ImageField(default=None, upload_to='img/'),
        ),
    ]
